import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { subscribeToUserCollection, addUserDoc, updateUserDoc, deleteUserDoc } from '../utils/userDataHelper';
import { num } from './utils/costCalculations';
import LabNavbar from './LabNavbar';

/**
 * Notifications - Manage reminders and alerts
 * Route: /lab/notifications
 * 
 * Features:
 * - Auto-generated alerts (low stock, curing complete, expiring soon)
 * - Custom reminders with due dates
 * - Notification preferences
 * - Browser push notifications (with permission)
 */

// Notification types with icons and colors
const NOTIFICATION_TYPES = {
  low_stock: { icon: '📦', color: '#ff9800', label: 'Low Stock' },
  curing_ready: { icon: '✅', color: '#4caf50', label: 'Curing Complete' },
  curing_soon: { icon: '⏰', color: '#2196f3', label: 'Curing Soon' },
  expiring: { icon: '⚠️', color: '#f44336', label: 'Expiring Soon' },
  reminder: { icon: '🔔', color: '#9c27b0', label: 'Reminder' },
  custom: { icon: '📝', color: '#607d8b', label: 'Custom' },
};

function Notifications() {
  const [ingredients, setIngredients] = useState([]);
  const [batches, setBatches] = useState([]);
  const [customReminders, setCustomReminders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showAddReminder, setShowAddReminder] = useState(false);
  const [newReminder, setNewReminder] = useState({ title: '', description: '', dueDate: '', priority: 'medium' });
  const [dismissedAlerts, setDismissedAlerts] = useState(() => {
    const saved = localStorage.getItem('dismissedAlerts');
    return saved ? JSON.parse(saved) : [];
  });
  const [notificationPermission, setNotificationPermission] = useState('default');

  // Check browser notification permission
  useEffect(() => {
    if ('Notification' in window) {
      setNotificationPermission(Notification.permission);
    }
  }, []);

  // Request notification permission
  const requestPermission = async () => {
    if ('Notification' in window) {
      const permission = await Notification.requestPermission();
      setNotificationPermission(permission);
      if (permission === 'granted') {
        new Notification('Soap Lab Notifications Enabled', {
          body: 'You will now receive alerts for important events.',
          icon: '🧪',
        });
      }
    }
  };

  // Load data
  useEffect(() => {
    const unsubs = [];

    try {
      unsubs.push(subscribeToUserCollection('ingredients', (data) => {
        setIngredients(data);
      }));

      unsubs.push(subscribeToUserCollection('batches', (data) => {
        setBatches(data);
      }));

      unsubs.push(subscribeToUserCollection('reminders', (data) => {
        // Sort by dueDate
        const sorted = [...data].sort((a, b) => {
          if (!a.dueDate) return 1;
          if (!b.dueDate) return -1;
          return new Date(a.dueDate) - new Date(b.dueDate);
        });
        setCustomReminders(sorted);
        setLoading(false);
      }));
    } catch (error) {
      console.error('Error loading data:', error);
      setLoading(false);
    }

    return () => unsubs.forEach(u => u());
  }, []);

  // Save dismissed alerts to localStorage
  useEffect(() => {
    localStorage.setItem('dismissedAlerts', JSON.stringify(dismissedAlerts));
  }, [dismissedAlerts]);

  // Generate automatic alerts
  const autoAlerts = useMemo(() => {
    const alerts = [];
    const today = new Date();

    // Low stock alerts
    ingredients.forEach(ing => {
      const stock = num(ing.stockGrams || ing.stock, 0);
      const minStock = num(ing.minStockGrams || ing.minStock || 100, 100);
      if (stock < minStock) {
        const alertId = `low_stock_${ing.id}`;
        if (!dismissedAlerts.includes(alertId)) {
          alerts.push({
            id: alertId,
            type: 'low_stock',
            title: `Low Stock: ${ing.name}`,
            description: `Only ${stock}g remaining (minimum: ${minStock}g)`,
            severity: stock < minStock * 0.5 ? 'high' : 'medium',
            itemId: ing.id,
            autoGenerated: true,
          });
        }
      }
    });

    // Batch curing alerts
    batches.forEach(batch => {
      if (batch.status === 'curing' && batch.madeDate) {
        const madeDate = new Date(batch.madeDate);
        const readyDate = new Date(madeDate.getTime() + 42 * 24 * 60 * 60 * 1000); // 6 weeks
        const daysLeft = Math.ceil((readyDate - today) / (1000 * 60 * 60 * 24));

        if (daysLeft <= 0) {
          const alertId = `curing_ready_${batch.id}`;
          if (!dismissedAlerts.includes(alertId)) {
            alerts.push({
              id: alertId,
              type: 'curing_ready',
              title: `Ready: ${batch.name || batch.recipeName || 'Batch'}`,
              description: `Curing complete! Ready for testing and sale.`,
              severity: 'high',
              itemId: batch.id,
              autoGenerated: true,
            });
          }
        } else if (daysLeft <= 7) {
          const alertId = `curing_soon_${batch.id}`;
          if (!dismissedAlerts.includes(alertId)) {
            alerts.push({
              id: alertId,
              type: 'curing_soon',
              title: `Almost Ready: ${batch.name || batch.recipeName || 'Batch'}`,
              description: `${daysLeft} day(s) until curing complete.`,
              severity: 'low',
              itemId: batch.id,
              autoGenerated: true,
            });
          }
        }
      }

      // Expiry alerts
      if (batch.soapExpiryDate) {
        const expDate = new Date(batch.soapExpiryDate);
        const daysToExpiry = Math.ceil((expDate - today) / (1000 * 60 * 60 * 24));

        if (daysToExpiry <= 30 && daysToExpiry > 0) {
          const alertId = `expiring_${batch.id}`;
          if (!dismissedAlerts.includes(alertId)) {
            alerts.push({
              id: alertId,
              type: 'expiring',
              title: `Expiring: ${batch.name || batch.recipeName || 'Batch'}`,
              description: `Expires in ${daysToExpiry} days. Consider selling or using soon.`,
              severity: daysToExpiry <= 7 ? 'high' : 'medium',
              itemId: batch.id,
              autoGenerated: true,
            });
          }
        }
      }
    });

    return alerts;
  }, [ingredients, batches, dismissedAlerts]);

  // Custom reminder alerts
  const reminderAlerts = useMemo(() => {
    const today = new Date();
    return customReminders
      .filter(r => !r.completed)
      .map(r => {
        const dueDate = r.dueDate ? new Date(r.dueDate) : null;
        const isOverdue = dueDate && dueDate < today;
        const isDueToday = dueDate && dueDate.toDateString() === today.toDateString();
        
        return {
          id: `reminder_${r.id}`,
          type: 'reminder',
          title: r.title,
          description: r.description || (dueDate ? `Due: ${dueDate.toLocaleDateString()}` : ''),
          severity: isOverdue ? 'high' : isDueToday ? 'medium' : 'low',
          dueDate: r.dueDate,
          reminderId: r.id,
          priority: r.priority,
          autoGenerated: false,
        };
      });
  }, [customReminders]);

  // All alerts combined
  const allAlerts = useMemo(() => {
    const combined = [...autoAlerts, ...reminderAlerts];
    // Sort by severity
    const severityOrder = { high: 0, medium: 1, low: 2 };
    return combined.sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity]);
  }, [autoAlerts, reminderAlerts]);

  // Dismiss an alert
  const dismissAlert = (alertId) => {
    setDismissedAlerts(prev => [...prev, alertId]);
  };

  // Reset dismissed alerts
  const resetDismissed = () => {
    setDismissedAlerts([]);
  };

  // Add custom reminder
  const addReminder = async () => {
    if (!newReminder.title.trim()) {
      alert('Please enter a title');
      return;
    }

    try {
      await addUserDoc('reminders', {
        ...newReminder,
        completed: false,
      });
      setNewReminder({ title: '', description: '', dueDate: '', priority: 'medium' });
      setShowAddReminder(false);
    } catch (error) {
      alert('Failed to add reminder: ' + error.message);
    }
  };

  // Mark reminder complete
  const completeReminder = async (reminderId) => {
    try {
      await updateUserDoc('reminders', reminderId, { completed: true });
    } catch (error) {
      console.error('Error completing reminder:', error);
    }
  };

  // Delete reminder
  const deleteReminder = async (reminderId) => {
    if (window.confirm('Delete this reminder?')) {
      try {
        await deleteUserDoc('reminders', reminderId);
      } catch (error) {
        console.error('Error deleting reminder:', error);
      }
    }
  };

  // Send browser notification (for future use with service workers)
  const sendBrowserNotification = useCallback((title, body) => {
    if (notificationPermission === 'granted') {
      new Notification(title, { body, icon: '🧪' });
    }
  }, [notificationPermission]);

  if (loading) {
    return (
      <div>
        <LabNavbar />
        <div style={{ maxWidth: 900, margin: '0 auto', padding: 24, textAlign: 'center' }}>
          <div style={{ fontSize: '2em', marginBottom: 16 }}>⏳</div>
          <div>Loading notifications...</div>
        </div>
      </div>
    );
  }

  const highPriorityCount = allAlerts.filter(a => a.severity === 'high').length;

  return (
    <div>
      <LabNavbar />
      <div style={{ maxWidth: 900, margin: '0 auto', padding: 16 }}>
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
          <div>
            <h1 style={{ margin: 0, fontSize: '1.8em' }}>
              🔔 Notifications
              {highPriorityCount > 0 && (
                <span style={{
                  marginLeft: 10,
                  padding: '4px 10px',
                  background: '#f44336',
                  color: '#fff',
                  borderRadius: 20,
                  fontSize: '0.5em',
                  verticalAlign: 'middle',
                }}>
                  {highPriorityCount} urgent
                </span>
              )}
            </h1>
            <p style={{ margin: '8px 0 0', color: '#666' }}>Alerts, reminders, and important notifications</p>
          </div>
          
          <div style={{ display: 'flex', gap: 10 }}>
            {dismissedAlerts.length > 0 && (
              <button
                onClick={resetDismissed}
                style={{
                  padding: '10px 16px',
                  background: '#f5f5f5',
                  border: '1px solid #ddd',
                  borderRadius: 6,
                  cursor: 'pointer',
                }}
              >
                Show Dismissed ({dismissedAlerts.length})
              </button>
            )}
            <button
              onClick={() => setShowAddReminder(true)}
              style={{
                padding: '10px 20px',
                background: '#1976d2',
                color: '#fff',
                border: 'none',
                borderRadius: 6,
                cursor: 'pointer',
                fontWeight: 600,
              }}
            >
              + Add Reminder
            </button>
          </div>
        </div>

        {/* Browser Notification Permission */}
        {notificationPermission !== 'granted' && (
          <div style={{
            padding: 16,
            marginBottom: 20,
            background: '#e3f2fd',
            borderRadius: 8,
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}>
            <div>
              <strong>Enable Browser Notifications</strong>
              <div style={{ fontSize: '0.9em', color: '#666' }}>Get notified even when this tab isn't active</div>
            </div>
            <button
              onClick={requestPermission}
              style={{
                padding: '8px 16px',
                background: '#1976d2',
                color: '#fff',
                border: 'none',
                borderRadius: 4,
                cursor: 'pointer',
              }}
            >
              Enable
            </button>
          </div>
        )}

        {/* Add Reminder Modal */}
        {showAddReminder && (
          <div style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: 'rgba(0,0,0,0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
          }}>
            <div style={{
              background: '#fff',
              borderRadius: 12,
              padding: 24,
              width: '90%',
              maxWidth: 450,
            }}>
              <h3 style={{ margin: '0 0 20px' }}>📝 Add Reminder</h3>
              
              <div style={{ marginBottom: 16 }}>
                <label style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Title *</label>
                <input
                  type="text"
                  value={newReminder.title}
                  onChange={(e) => setNewReminder(prev => ({ ...prev, title: e.target.value }))}
                  placeholder="What do you need to remember?"
                  style={{ width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 6, fontSize: '1em' }}
                />
              </div>

              <div style={{ marginBottom: 16 }}>
                <label style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Description</label>
                <textarea
                  value={newReminder.description}
                  onChange={(e) => setNewReminder(prev => ({ ...prev, description: e.target.value }))}
                  placeholder="Additional details..."
                  rows={3}
                  style={{ width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 6, fontSize: '1em', resize: 'vertical' }}
                />
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 20 }}>
                <div>
                  <label style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Due Date</label>
                  <input
                    type="date"
                    value={newReminder.dueDate}
                    onChange={(e) => setNewReminder(prev => ({ ...prev, dueDate: e.target.value }))}
                    style={{ width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 6, fontSize: '1em' }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Priority</label>
                  <select
                    value={newReminder.priority}
                    onChange={(e) => setNewReminder(prev => ({ ...prev, priority: e.target.value }))}
                    style={{ width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 6, fontSize: '1em' }}
                  >
                    <option value="low">Low</option>
                    <option value="medium">Medium</option>
                    <option value="high">High</option>
                  </select>
                </div>
              </div>

              <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
                <button
                  onClick={() => setShowAddReminder(false)}
                  style={{ padding: '10px 20px', background: '#eee', border: 'none', borderRadius: 6, cursor: 'pointer' }}
                >
                  Cancel
                </button>
                <button
                  onClick={addReminder}
                  style={{ padding: '10px 20px', background: '#4caf50', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer', fontWeight: 600 }}
                >
                  Add Reminder
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Alerts List */}
        {allAlerts.length === 0 ? (
          <div style={{ padding: 60, textAlign: 'center', background: '#e8f5e9', borderRadius: 12 }}>
            <div style={{ fontSize: '4em', marginBottom: 16 }}>✅</div>
            <div style={{ fontSize: '1.3em', fontWeight: 600, color: '#2e7d32' }}>All clear!</div>
            <div style={{ color: '#666', marginTop: 8 }}>No notifications or reminders at the moment.</div>
          </div>
        ) : (
          <div style={{ display: 'grid', gap: 12 }}>
            {allAlerts.map(alert => {
              const typeInfo = NOTIFICATION_TYPES[alert.type] || NOTIFICATION_TYPES.custom;
              return (
                <div
                  key={alert.id}
                  style={{
                    padding: 16,
                    background: '#fff',
                    borderRadius: 10,
                    border: `2px solid ${alert.severity === 'high' ? '#f44336' : alert.severity === 'medium' ? '#ff9800' : '#e0e0e0'}`,
                    display: 'flex',
                    gap: 14,
                    alignItems: 'flex-start',
                  }}
                >
                  <div style={{
                    width: 44,
                    height: 44,
                    borderRadius: '50%',
                    background: typeInfo.color,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '1.4em',
                    flexShrink: 0,
                  }}>
                    {typeInfo.icon}
                  </div>
                  
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                      <span style={{ fontWeight: 600, fontSize: '1.05em' }}>{alert.title}</span>
                      {alert.severity === 'high' && (
                        <span style={{ padding: '2px 8px', background: '#ffebee', color: '#c62828', borderRadius: 4, fontSize: '0.75em', fontWeight: 600 }}>
                          URGENT
                        </span>
                      )}
                    </div>
                    <div style={{ color: '#666', fontSize: '0.9em' }}>{alert.description}</div>
                    <div style={{ marginTop: 8, fontSize: '0.8em', color: '#999' }}>
                      <span style={{ 
                        padding: '2px 8px', 
                        background: typeInfo.color + '20', 
                        borderRadius: 4,
                      }}>
                        {typeInfo.label}
                      </span>
                      {alert.autoGenerated && <span style={{ marginLeft: 8 }}>• Auto-generated</span>}
                    </div>
                  </div>

                  <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}>
                    {alert.reminderId && (
                      <>
                        <button
                          onClick={() => completeReminder(alert.reminderId)}
                          style={{
                            padding: '8px 12px',
                            background: '#4caf50',
                            color: '#fff',
                            border: 'none',
                            borderRadius: 4,
                            cursor: 'pointer',
                            fontSize: '0.85em',
                          }}
                        >
                          ✓ Done
                        </button>
                        <button
                          onClick={() => deleteReminder(alert.reminderId)}
                          style={{
                            padding: '8px 12px',
                            background: '#f44336',
                            color: '#fff',
                            border: 'none',
                            borderRadius: 4,
                            cursor: 'pointer',
                            fontSize: '0.85em',
                          }}
                        >
                          🗑️
                        </button>
                      </>
                    )}
                    {alert.autoGenerated && (
                      <button
                        onClick={() => dismissAlert(alert.id)}
                        style={{
                          padding: '8px 12px',
                          background: '#f5f5f5',
                          border: '1px solid #ddd',
                          borderRadius: 4,
                          cursor: 'pointer',
                          fontSize: '0.85em',
                        }}
                      >
                        Dismiss
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Completed Reminders */}
        {customReminders.filter(r => r.completed).length > 0 && (
          <div style={{ marginTop: 32 }}>
            <h3 style={{ margin: '0 0 12px', fontSize: '1.1em', color: '#666' }}>✅ Completed Reminders</h3>
            <div style={{ display: 'grid', gap: 8 }}>
              {customReminders.filter(r => r.completed).map(r => (
                <div key={r.id} style={{
                  padding: 12,
                  background: '#f5f5f5',
                  borderRadius: 6,
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  opacity: 0.7,
                }}>
                  <span style={{ textDecoration: 'line-through' }}>{r.title}</span>
                  <button
                    onClick={() => deleteReminder(r.id)}
                    style={{
                      padding: '4px 8px',
                      background: 'transparent',
                      border: 'none',
                      cursor: 'pointer',
                      color: '#999',
                    }}
                  >
                    🗑️
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default Notifications;
